# To create the conda environment:
# $ conda env create -n data_gen -f conda.yaml
#
# To update the conda environment:
# $ conda env update -n data_gen -f conda.yaml
#
# To register the conda environment in Jupyter:
# $ source activate data_gen
# $ python -m ipykernel install --user --name data_gen --display-name "Python (data_gen)"
#

channels:
- conda-forge
- defaults
dependencies:
- python==3.6.8
- numpy==1.16.4
- pandas==0.24.2
- ipykernel==5.1.1
- opencv==3.4.1
- imgaug==0.2.9
- pip:
  - tornado==6.0.3
  - jupyter==1.0.0
  - matplotlib==3.1.1
  - Pillow==6.1.0
  - scikit-image==0.15.0
  - scipy==1.3.0
  - nltk==3.4.4
  - requests==2.22.0
  - transforms3d==0.3.1

